source 'https://rubygems.org'
gem 'meshtastic', path: 'gems/meshtastic'
gem 'sinatra'
gem 'activerecord', '~> 7', require: 'active_record'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'rake'
gem 'sqlite3'
gem 'pry'
gem 'rack'
gem 'embiggen', '~> 1.6'
gem 'rexml'
gem 'json-repair'
gem 'colorize'

gem 'log_it', path: 'gems/log_it'
gem 'string', path: 'gems/string'
gem 'time_utilities', path: 'gems/time_utilities'
gem 'meshtastic_cli', path: 'gems/meshtastic_cli'

gem 'help', path: 'gems/help'
gem 'about', path: 'gems/about'
gem 'ping', path: 'gems/ping'
gem 'joke', path: 'gems/joke'
gem 'riddle', path: 'gems/riddle'
gem 'insult', path: 'gems/insult'
gem 'weather', path: 'gems/weather'
gem 'fact', path: 'gems/fact'
gem 'techy', path: 'gems/techy'
gem 'corporate', path: 'gems/corporate'
gem 'chuck', path: 'gems/chuck'
gem 'callsign', path: 'gems/callsign'
gem 'google_ai', path: 'gems/google_ai'
gem 'coin', path: 'gems/coin'
gem 'eight_ball', path: 'gems/eight_ball'
gem 'poop', path: 'gems/poop'
gem 'recall', path: 'gems/recall'
gem 'seen', path: 'gems/seen'
gem 'whois', path: 'gems/whois'

gem 'calendar', path: 'gems/calendar'
gem 'clock', path: 'gems/clock'
gem 'greetings', path: 'gems/greetings'
gem 'ignore', path: 'gems/ignore'
gem 'laugh', path: 'gems/laugh'
gem 'marco', path: 'gems/marco'
gem 'notice_manager', path: 'gems/notice_manager'
gem 'shutdown', path: 'gems/shutdown'
gem 'test', path: 'gems/test'
gem 'url_resolver', path: 'gems/url_resolver'
gem 'trivia', path: 'gems/trivia'
gem 'reboot', path: 'gems/reboot'
# gem 'yo_momma', path: 'gems/yo_momma'
gem 'rx_bot', path: 'gems/rx_bot'
gem 'tx_bot', path: 'gems/tx_bot'
# gem 'notices_bot', path: 'gems/notices_bot'
gem 'censor', path: 'gems/censor'