source 'https://rubygems.org'
gem 'meshtastic', path: 'gems/meshtastic'
gem 'sinatra'
gem 'activerecord', '~> 7', require: 'active_record'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'rake'
gem 'sqlite3'
gem 'pry'
gem 'rack'
gem 'embiggen', '~> 1.6'

gem 'calendar', path: 'gems/calendar'
gem 'clock', path: 'gems/clock'
gem 'coin', path: 'gems/coin'
gem 'eight_ball', path: 'gems/eight_ball'
# gem 'google_ai', path: 'gems/google_ai'
gem 'greetings', path: 'gems/greetings'
gem 'help', path: 'gems/help'
gem 'ignore', path: 'gems/ignore'
gem 'info', path: 'gems/info'
gem 'insult', path: 'gems/insult'
gem 'laugh', path: 'gems/laugh'
gem 'log_it', path: 'gems/log_it'
gem 'marco', path: 'gems/marco'
gem 'notice_setter', path: 'gems/notice_setter'
gem 'ping', path: 'gems/ping'
gem 'seen', path: 'gems/seen'
gem 'shutdown', path: 'gems/shutdown'
gem 'string', path: 'gems/string'
# gem 'test', path: 'gems/test'
gem 'time_utilities', path: 'gems/time_utilities'
gem 'url_resolver', path: 'gems/url_resolver'
gem 'joke', path: 'gems/joke'
gem 'riddle', path: 'gems/riddle'
# gem 'trivia', path: 'gems/trivia'
gem 'whois', path: 'gems/whois'
# gem 'weather', path: 'gems/weather'
gem 'message_queue', path: 'gems/message_queue'
gem 'rexml'
gem 'json-repair'
gem 'meshtastic_cli', path: 'gems/meshtastic_cli'
gem 'colorize'