# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/admin.proto

require 'google/protobuf'

require 'meshtastic/channel_pb'
require 'meshtastic/config_pb'
require 'meshtastic/connection_status_pb'
require 'meshtastic/mesh_pb'
require 'meshtastic/module_config_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/admin.proto", :syntax => :proto3) do
    add_message "meshtastic.AdminMessage" do
      oneof :payload_variant do
        optional :get_channel_request, :uint32, 1
        optional :get_channel_response, :message, 2, "meshtastic.Channel"
        optional :get_owner_request, :bool, 3
        optional :get_owner_response, :message, 4, "meshtastic.User"
        optional :get_config_request, :enum, 5, "meshtastic.AdminMessage.ConfigType"
        optional :get_config_response, :message, 6, "meshtastic.Config"
        optional :get_module_config_request, :enum, 7, "meshtastic.AdminMessage.ModuleConfigType"
        optional :get_module_config_response, :message, 8, "meshtastic.ModuleConfig"
        optional :get_canned_message_module_messages_request, :bool, 10
        optional :get_canned_message_module_messages_response, :string, 11
        optional :get_device_metadata_request, :bool, 12
        optional :get_device_metadata_response, :message, 13, "meshtastic.DeviceMetadata"
        optional :get_ringtone_request, :bool, 14
        optional :get_ringtone_response, :string, 15
        optional :get_device_connection_status_request, :bool, 16
        optional :get_device_connection_status_response, :message, 17, "meshtastic.DeviceConnectionStatus"
        optional :set_ham_mode, :message, 18, "meshtastic.HamParameters"
        optional :get_node_remote_hardware_pins_request, :bool, 19
        optional :get_node_remote_hardware_pins_response, :message, 20, "meshtastic.NodeRemoteHardwarePinsResponse"
        optional :enter_dfu_mode_request, :bool, 21
        optional :delete_file_request, :string, 22
        optional :set_owner, :message, 32, "meshtastic.User"
        optional :set_channel, :message, 33, "meshtastic.Channel"
        optional :set_config, :message, 34, "meshtastic.Config"
        optional :set_module_config, :message, 35, "meshtastic.ModuleConfig"
        optional :set_canned_message_module_messages, :string, 36
        optional :set_ringtone_message, :string, 37
        optional :remove_by_nodenum, :uint32, 38
        optional :set_favorite_node, :uint32, 39
        optional :remove_favorite_node, :uint32, 40
        optional :set_fixed_position, :message, 41, "meshtastic.Position"
        optional :remove_fixed_position, :bool, 42
        optional :begin_edit_settings, :bool, 64
        optional :commit_edit_settings, :bool, 65
        optional :reboot_ota_seconds, :int32, 95
        optional :exit_simulator, :bool, 96
        optional :reboot_seconds, :int32, 97
        optional :shutdown_seconds, :int32, 98
        optional :factory_reset, :int32, 99
        optional :nodedb_reset, :int32, 100
      end
    end
    add_enum "meshtastic.AdminMessage.ConfigType" do
      value :DEVICE_CONFIG, 0
      value :POSITION_CONFIG, 1
      value :POWER_CONFIG, 2
      value :NETWORK_CONFIG, 3
      value :DISPLAY_CONFIG, 4
      value :LORA_CONFIG, 5
      value :BLUETOOTH_CONFIG, 6
    end
    add_enum "meshtastic.AdminMessage.ModuleConfigType" do
      value :MQTT_CONFIG, 0
      value :SERIAL_CONFIG, 1
      value :EXTNOTIF_CONFIG, 2
      value :STOREFORWARD_CONFIG, 3
      value :RANGETEST_CONFIG, 4
      value :TELEMETRY_CONFIG, 5
      value :CANNEDMSG_CONFIG, 6
      value :AUDIO_CONFIG, 7
      value :REMOTEHARDWARE_CONFIG, 8
      value :NEIGHBORINFO_CONFIG, 9
      value :AMBIENTLIGHTING_CONFIG, 10
      value :DETECTIONSENSOR_CONFIG, 11
      value :PAXCOUNTER_CONFIG, 12
    end
    add_message "meshtastic.HamParameters" do
      optional :call_sign, :string, 1
      optional :tx_power, :int32, 2
      optional :frequency, :float, 3
      optional :short_name, :string, 4
    end
    add_message "meshtastic.NodeRemoteHardwarePinsResponse" do
      repeated :node_remote_hardware_pins, :message, 1, "meshtastic.NodeRemoteHardwarePin"
    end
  end
end

module Meshtastic
  AdminMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.AdminMessage").msgclass
  AdminMessage::ConfigType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.AdminMessage.ConfigType").enummodule
  AdminMessage::ModuleConfigType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.AdminMessage.ModuleConfigType").enummodule
  HamParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.HamParameters").msgclass
  NodeRemoteHardwarePinsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.NodeRemoteHardwarePinsResponse").msgclass
end
