# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/apponly.proto

require 'google/protobuf'

require 'meshtastic/channel_pb'
require 'meshtastic/config_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/apponly.proto", :syntax => :proto3) do
    add_message "meshtastic.ChannelSet" do
      repeated :settings, :message, 1, "meshtastic.ChannelSettings"
      optional :lora_config, :message, 2, "meshtastic.Config.LoRaConfig"
    end
  end
end

module Meshtastic
  ChannelSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.ChannelSet").msgclass
end
