# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/atak.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/atak.proto", :syntax => :proto3) do
    add_message "meshtastic.TAKPacket" do
      optional :is_compressed, :bool, 1
      optional :contact, :message, 2, "meshtastic.Contact"
      optional :group, :message, 3, "meshtastic.Group"
      optional :status, :message, 4, "meshtastic.Status"
      oneof :payload_variant do
        optional :pli, :message, 5, "meshtastic.PLI"
        optional :chat, :message, 6, "meshtastic.GeoChat"
      end
    end
    add_message "meshtastic.GeoChat" do
      optional :message, :string, 1
      proto3_optional :to, :string, 2
    end
    add_message "meshtastic.Group" do
      optional :role, :enum, 1, "meshtastic.MemberRole"
      optional :team, :enum, 2, "meshtastic.Team"
    end
    add_message "meshtastic.Status" do
      optional :battery, :uint32, 1
    end
    add_message "meshtastic.Contact" do
      optional :callsign, :string, 1
      optional :device_callsign, :string, 2
    end
    add_message "meshtastic.PLI" do
      optional :latitude_i, :sfixed32, 1
      optional :longitude_i, :sfixed32, 2
      optional :altitude, :int32, 3
      optional :speed, :uint32, 4
      optional :course, :uint32, 5
    end
    add_enum "meshtastic.Team" do
      value :Unspecifed_Color, 0
      value :White, 1
      value :Yellow, 2
      value :Orange, 3
      value :Magenta, 4
      value :Red, 5
      value :Maroon, 6
      value :Purple, 7
      value :Dark_Blue, 8
      value :Blue, 9
      value :Cyan, 10
      value :Teal, 11
      value :Green, 12
      value :Dark_Green, 13
      value :Brown, 14
    end
    add_enum "meshtastic.MemberRole" do
      value :Unspecifed, 0
      value :TeamMember, 1
      value :TeamLead, 2
      value :HQ, 3
      value :Sniper, 4
      value :Medic, 5
      value :ForwardObserver, 6
      value :RTO, 7
      value :K9, 8
    end
  end
end

module Meshtastic
  TAKPacket = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.TAKPacket").msgclass
  GeoChat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.GeoChat").msgclass
  Group = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Group").msgclass
  Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Status").msgclass
  Contact = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Contact").msgclass
  PLI = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.PLI").msgclass
  Team = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Team").enummodule
  MemberRole = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.MemberRole").enummodule
end
