# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/cannedmessages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/cannedmessages.proto", :syntax => :proto3) do
    add_message "meshtastic.CannedMessageModuleConfig" do
      optional :messages, :string, 1
    end
  end
end

module Meshtastic
  CannedMessageModuleConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.CannedMessageModuleConfig").msgclass
end
