# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/channel.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/channel.proto", :syntax => :proto3) do
    add_message "meshtastic.ChannelSettings" do
      optional :channel_num, :uint32, 1
      optional :psk, :bytes, 2
      optional :name, :string, 3
      optional :id, :fixed32, 4
      optional :uplink_enabled, :bool, 5
      optional :downlink_enabled, :bool, 6
      optional :module_settings, :message, 7, "meshtastic.ModuleSettings"
    end
    add_message "meshtastic.ModuleSettings" do
      optional :position_precision, :uint32, 1
    end
    add_message "meshtastic.Channel" do
      optional :index, :int32, 1
      optional :settings, :message, 2, "meshtastic.ChannelSettings"
      optional :role, :enum, 3, "meshtastic.Channel.Role"
    end
    add_enum "meshtastic.Channel.Role" do
      value :DISABLED, 0
      value :PRIMARY, 1
      value :SECONDARY, 2
    end
  end
end

module Meshtastic
  ChannelSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.ChannelSettings").msgclass
  ModuleSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.ModuleSettings").msgclass
  Channel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Channel").msgclass
  Channel::Role = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Channel.Role").enummodule
end
