# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/config.proto", :syntax => :proto3) do
    add_message "meshtastic.Config" do
      oneof :payload_variant do
        optional :device, :message, 1, "meshtastic.Config.DeviceConfig"
        optional :position, :message, 2, "meshtastic.Config.PositionConfig"
        optional :power, :message, 3, "meshtastic.Config.PowerConfig"
        optional :network, :message, 4, "meshtastic.Config.NetworkConfig"
        optional :display, :message, 5, "meshtastic.Config.DisplayConfig"
        optional :lora, :message, 6, "meshtastic.Config.LoRaConfig"
        optional :bluetooth, :message, 7, "meshtastic.Config.BluetoothConfig"
      end
    end
    add_message "meshtastic.Config.DeviceConfig" do
      optional :role, :enum, 1, "meshtastic.Config.DeviceConfig.Role"
      optional :serial_enabled, :bool, 2
      optional :debug_log_enabled, :bool, 3
      optional :button_gpio, :uint32, 4
      optional :buzzer_gpio, :uint32, 5
      optional :rebroadcast_mode, :enum, 6, "meshtastic.Config.DeviceConfig.RebroadcastMode"
      optional :node_info_broadcast_secs, :uint32, 7
      optional :double_tap_as_button_press, :bool, 8
      optional :is_managed, :bool, 9
      optional :disable_triple_click, :bool, 10
      optional :tzdef, :string, 11
      optional :led_heartbeat_disabled, :bool, 12
    end
    add_enum "meshtastic.Config.DeviceConfig.Role" do
      value :CLIENT, 0
      value :CLIENT_MUTE, 1
      value :ROUTER, 2
      value :ROUTER_CLIENT, 3
      value :REPEATER, 4
      value :TRACKER, 5
      value :SENSOR, 6
      value :TAK, 7
      value :CLIENT_HIDDEN, 8
      value :LOST_AND_FOUND, 9
      value :TAK_TRACKER, 10
    end
    add_enum "meshtastic.Config.DeviceConfig.RebroadcastMode" do
      value :ALL, 0
      value :ALL_SKIP_DECODING, 1
      value :LOCAL_ONLY, 2
      value :KNOWN_ONLY, 3
    end
    add_message "meshtastic.Config.PositionConfig" do
      optional :position_broadcast_secs, :uint32, 1
      optional :position_broadcast_smart_enabled, :bool, 2
      optional :fixed_position, :bool, 3
      optional :gps_enabled, :bool, 4
      optional :gps_update_interval, :uint32, 5
      optional :gps_attempt_time, :uint32, 6
      optional :position_flags, :uint32, 7
      optional :rx_gpio, :uint32, 8
      optional :tx_gpio, :uint32, 9
      optional :broadcast_smart_minimum_distance, :uint32, 10
      optional :broadcast_smart_minimum_interval_secs, :uint32, 11
      optional :gps_en_gpio, :uint32, 12
      optional :gps_mode, :enum, 13, "meshtastic.Config.PositionConfig.GpsMode"
    end
    add_enum "meshtastic.Config.PositionConfig.PositionFlags" do
      value :UNSET, 0
      value :ALTITUDE, 1
      value :ALTITUDE_MSL, 2
      value :GEOIDAL_SEPARATION, 4
      value :DOP, 8
      value :HVDOP, 16
      value :SATINVIEW, 32
      value :SEQ_NO, 64
      value :TIMESTAMP, 128
      value :HEADING, 256
      value :SPEED, 512
    end
    add_enum "meshtastic.Config.PositionConfig.GpsMode" do
      value :DISABLED, 0
      value :ENABLED, 1
      value :NOT_PRESENT, 2
    end
    add_message "meshtastic.Config.PowerConfig" do
      optional :is_power_saving, :bool, 1
      optional :on_battery_shutdown_after_secs, :uint32, 2
      optional :adc_multiplier_override, :float, 3
      optional :wait_bluetooth_secs, :uint32, 4
      optional :sds_secs, :uint32, 6
      optional :ls_secs, :uint32, 7
      optional :min_wake_secs, :uint32, 8
      optional :device_battery_ina_address, :uint32, 9
    end
    add_message "meshtastic.Config.NetworkConfig" do
      optional :wifi_enabled, :bool, 1
      optional :wifi_ssid, :string, 3
      optional :wifi_psk, :string, 4
      optional :ntp_server, :string, 5
      optional :eth_enabled, :bool, 6
      optional :address_mode, :enum, 7, "meshtastic.Config.NetworkConfig.AddressMode"
      optional :ipv4_config, :message, 8, "meshtastic.Config.NetworkConfig.IpV4Config"
      optional :rsyslog_server, :string, 9
    end
    add_message "meshtastic.Config.NetworkConfig.IpV4Config" do
      optional :ip, :fixed32, 1
      optional :gateway, :fixed32, 2
      optional :subnet, :fixed32, 3
      optional :dns, :fixed32, 4
    end
    add_enum "meshtastic.Config.NetworkConfig.AddressMode" do
      value :DHCP, 0
      value :STATIC, 1
    end
    add_message "meshtastic.Config.DisplayConfig" do
      optional :screen_on_secs, :uint32, 1
      optional :gps_format, :enum, 2, "meshtastic.Config.DisplayConfig.GpsCoordinateFormat"
      optional :auto_screen_carousel_secs, :uint32, 3
      optional :compass_north_top, :bool, 4
      optional :flip_screen, :bool, 5
      optional :units, :enum, 6, "meshtastic.Config.DisplayConfig.DisplayUnits"
      optional :oled, :enum, 7, "meshtastic.Config.DisplayConfig.OledType"
      optional :displaymode, :enum, 8, "meshtastic.Config.DisplayConfig.DisplayMode"
      optional :heading_bold, :bool, 9
      optional :wake_on_tap_or_motion, :bool, 10
    end
    add_enum "meshtastic.Config.DisplayConfig.GpsCoordinateFormat" do
      value :DEC, 0
      value :DMS, 1
      value :UTM, 2
      value :MGRS, 3
      value :OLC, 4
      value :OSGR, 5
    end
    add_enum "meshtastic.Config.DisplayConfig.DisplayUnits" do
      value :METRIC, 0
      value :IMPERIAL, 1
    end
    add_enum "meshtastic.Config.DisplayConfig.OledType" do
      value :OLED_AUTO, 0
      value :OLED_SSD1306, 1
      value :OLED_SH1106, 2
      value :OLED_SH1107, 3
    end
    add_enum "meshtastic.Config.DisplayConfig.DisplayMode" do
      value :DEFAULT, 0
      value :TWOCOLOR, 1
      value :INVERTED, 2
      value :COLOR, 3
    end
    add_message "meshtastic.Config.LoRaConfig" do
      optional :use_preset, :bool, 1
      optional :modem_preset, :enum, 2, "meshtastic.Config.LoRaConfig.ModemPreset"
      optional :bandwidth, :uint32, 3
      optional :spread_factor, :uint32, 4
      optional :coding_rate, :uint32, 5
      optional :frequency_offset, :float, 6
      optional :region, :enum, 7, "meshtastic.Config.LoRaConfig.RegionCode"
      optional :hop_limit, :uint32, 8
      optional :tx_enabled, :bool, 9
      optional :tx_power, :int32, 10
      optional :channel_num, :uint32, 11
      optional :override_duty_cycle, :bool, 12
      optional :sx126x_rx_boosted_gain, :bool, 13
      optional :override_frequency, :float, 14
      repeated :ignore_incoming, :uint32, 103
      optional :ignore_mqtt, :bool, 104
    end
    add_enum "meshtastic.Config.LoRaConfig.RegionCode" do
      value :UNSET, 0
      value :US, 1
      value :EU_433, 2
      value :EU_868, 3
      value :CN, 4
      value :JP, 5
      value :ANZ, 6
      value :KR, 7
      value :TW, 8
      value :RU, 9
      value :IN, 10
      value :NZ_865, 11
      value :TH, 12
      value :LORA_24, 13
      value :UA_433, 14
      value :UA_868, 15
      value :MY_433, 16
      value :MY_919, 17
      value :SG_923, 18
    end
    add_enum "meshtastic.Config.LoRaConfig.ModemPreset" do
      value :LONG_FAST, 0
      value :LONG_SLOW, 1
      value :VERY_LONG_SLOW, 2
      value :MEDIUM_SLOW, 3
      value :MEDIUM_FAST, 4
      value :SHORT_SLOW, 5
      value :SHORT_FAST, 6
      value :LONG_MODERATE, 7
    end
    add_message "meshtastic.Config.BluetoothConfig" do
      optional :enabled, :bool, 1
      optional :mode, :enum, 2, "meshtastic.Config.BluetoothConfig.PairingMode"
      optional :fixed_pin, :uint32, 3
    end
    add_enum "meshtastic.Config.BluetoothConfig.PairingMode" do
      value :RANDOM_PIN, 0
      value :FIXED_PIN, 1
      value :NO_PIN, 2
    end
  end
end

module Meshtastic
  Config = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config").msgclass
  Config::DeviceConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.DeviceConfig").msgclass
  Config::DeviceConfig::Role = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.DeviceConfig.Role").enummodule
  Config::DeviceConfig::RebroadcastMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.DeviceConfig.RebroadcastMode").enummodule
  Config::PositionConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.PositionConfig").msgclass
  Config::PositionConfig::PositionFlags = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.PositionConfig.PositionFlags").enummodule
  Config::PositionConfig::GpsMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.PositionConfig.GpsMode").enummodule
  Config::PowerConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.PowerConfig").msgclass
  Config::NetworkConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.NetworkConfig").msgclass
  Config::NetworkConfig::IpV4Config = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.NetworkConfig.IpV4Config").msgclass
  Config::NetworkConfig::AddressMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.NetworkConfig.AddressMode").enummodule
  Config::DisplayConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.DisplayConfig").msgclass
  Config::DisplayConfig::GpsCoordinateFormat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.DisplayConfig.GpsCoordinateFormat").enummodule
  Config::DisplayConfig::DisplayUnits = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.DisplayConfig.DisplayUnits").enummodule
  Config::DisplayConfig::OledType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.DisplayConfig.OledType").enummodule
  Config::DisplayConfig::DisplayMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.DisplayConfig.DisplayMode").enummodule
  Config::LoRaConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.LoRaConfig").msgclass
  Config::LoRaConfig::RegionCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.LoRaConfig.RegionCode").enummodule
  Config::LoRaConfig::ModemPreset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.LoRaConfig.ModemPreset").enummodule
  Config::BluetoothConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.BluetoothConfig").msgclass
  Config::BluetoothConfig::PairingMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Config.BluetoothConfig.PairingMode").enummodule
end
