# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/connection_status.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/connection_status.proto", :syntax => :proto3) do
    add_message "meshtastic.DeviceConnectionStatus" do
      proto3_optional :wifi, :message, 1, "meshtastic.WifiConnectionStatus"
      proto3_optional :ethernet, :message, 2, "meshtastic.EthernetConnectionStatus"
      proto3_optional :bluetooth, :message, 3, "meshtastic.BluetoothConnectionStatus"
      proto3_optional :serial, :message, 4, "meshtastic.SerialConnectionStatus"
    end
    add_message "meshtastic.WifiConnectionStatus" do
      optional :status, :message, 1, "meshtastic.NetworkConnectionStatus"
      optional :ssid, :string, 2
      optional :rssi, :int32, 3
    end
    add_message "meshtastic.EthernetConnectionStatus" do
      optional :status, :message, 1, "meshtastic.NetworkConnectionStatus"
    end
    add_message "meshtastic.NetworkConnectionStatus" do
      optional :ip_address, :fixed32, 1
      optional :is_connected, :bool, 2
      optional :is_mqtt_connected, :bool, 3
      optional :is_syslog_connected, :bool, 4
    end
    add_message "meshtastic.BluetoothConnectionStatus" do
      optional :pin, :uint32, 1
      optional :rssi, :int32, 2
      optional :is_connected, :bool, 3
    end
    add_message "meshtastic.SerialConnectionStatus" do
      optional :baud, :uint32, 1
      optional :is_connected, :bool, 2
    end
  end
end

module Meshtastic
  DeviceConnectionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.DeviceConnectionStatus").msgclass
  WifiConnectionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.WifiConnectionStatus").msgclass
  EthernetConnectionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.EthernetConnectionStatus").msgclass
  NetworkConnectionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.NetworkConnectionStatus").msgclass
  BluetoothConnectionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.BluetoothConnectionStatus").msgclass
  SerialConnectionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.SerialConnectionStatus").msgclass
end
