# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/deviceonly.proto

require 'google/protobuf'

require 'meshtastic/channel_pb'
require 'meshtastic/localonly_pb'
require 'meshtastic/mesh_pb'
require 'meshtastic/module_config_pb'
require 'meshtastic/telemetry_pb'
require 'nanopb_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/deviceonly.proto", :syntax => :proto3) do
    add_message "meshtastic.PositionLite" do
      optional :latitude_i, :sfixed32, 1
      optional :longitude_i, :sfixed32, 2
      optional :altitude, :int32, 3
      optional :time, :fixed32, 4
      optional :location_source, :enum, 5, "meshtastic.Position.LocSource"
    end
    add_message "meshtastic.NodeInfoLite" do
      optional :num, :uint32, 1
      optional :user, :message, 2, "meshtastic.User"
      optional :position, :message, 3, "meshtastic.PositionLite"
      optional :snr, :float, 4
      optional :last_heard, :fixed32, 5
      optional :device_metrics, :message, 6, "meshtastic.DeviceMetrics"
      optional :channel, :uint32, 7
      optional :via_mqtt, :bool, 8
      optional :hops_away, :uint32, 9
      optional :is_favorite, :bool, 10
    end
    add_message "meshtastic.DeviceState" do
      optional :my_node, :message, 2, "meshtastic.MyNodeInfo"
      optional :owner, :message, 3, "meshtastic.User"
      repeated :receive_queue, :message, 5, "meshtastic.MeshPacket"
      optional :version, :uint32, 8
      optional :rx_text_message, :message, 7, "meshtastic.MeshPacket"
      optional :no_save, :bool, 9
      optional :did_gps_reset, :bool, 11
      optional :rx_waypoint, :message, 12, "meshtastic.MeshPacket"
      repeated :node_remote_hardware_pins, :message, 13, "meshtastic.NodeRemoteHardwarePin"
      repeated :node_db_lite, :message, 14, "meshtastic.NodeInfoLite"
    end
    add_message "meshtastic.ChannelFile" do
      repeated :channels, :message, 1, "meshtastic.Channel"
      optional :version, :uint32, 2
    end
    add_message "meshtastic.OEMStore" do
      optional :oem_icon_width, :uint32, 1
      optional :oem_icon_height, :uint32, 2
      optional :oem_icon_bits, :bytes, 3
      optional :oem_font, :enum, 4, "meshtastic.ScreenFonts"
      optional :oem_text, :string, 5
      optional :oem_aes_key, :bytes, 6
      optional :oem_local_config, :message, 7, "meshtastic.LocalConfig"
      optional :oem_local_module_config, :message, 8, "meshtastic.LocalModuleConfig"
    end
    add_enum "meshtastic.ScreenFonts" do
      value :FONT_SMALL, 0
      value :FONT_MEDIUM, 1
      value :FONT_LARGE, 2
    end
  end
end

module Meshtastic
  PositionLite = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.PositionLite").msgclass
  NodeInfoLite = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.NodeInfoLite").msgclass
  DeviceState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.DeviceState").msgclass
  ChannelFile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.ChannelFile").msgclass
  OEMStore = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.OEMStore").msgclass
  ScreenFonts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.ScreenFonts").enummodule
end
