# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/localonly.proto

require 'google/protobuf'

require 'meshtastic/config_pb'
require 'meshtastic/module_config_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/localonly.proto", :syntax => :proto3) do
    add_message "meshtastic.LocalConfig" do
      optional :device, :message, 1, "meshtastic.Config.DeviceConfig"
      optional :position, :message, 2, "meshtastic.Config.PositionConfig"
      optional :power, :message, 3, "meshtastic.Config.PowerConfig"
      optional :network, :message, 4, "meshtastic.Config.NetworkConfig"
      optional :display, :message, 5, "meshtastic.Config.DisplayConfig"
      optional :lora, :message, 6, "meshtastic.Config.LoRaConfig"
      optional :bluetooth, :message, 7, "meshtastic.Config.BluetoothConfig"
      optional :version, :uint32, 8
    end
    add_message "meshtastic.LocalModuleConfig" do
      optional :mqtt, :message, 1, "meshtastic.ModuleConfig.MQTTConfig"
      optional :serial, :message, 2, "meshtastic.ModuleConfig.SerialConfig"
      optional :external_notification, :message, 3, "meshtastic.ModuleConfig.ExternalNotificationConfig"
      optional :store_forward, :message, 4, "meshtastic.ModuleConfig.StoreForwardConfig"
      optional :range_test, :message, 5, "meshtastic.ModuleConfig.RangeTestConfig"
      optional :telemetry, :message, 6, "meshtastic.ModuleConfig.TelemetryConfig"
      optional :canned_message, :message, 7, "meshtastic.ModuleConfig.CannedMessageConfig"
      optional :audio, :message, 9, "meshtastic.ModuleConfig.AudioConfig"
      optional :remote_hardware, :message, 10, "meshtastic.ModuleConfig.RemoteHardwareConfig"
      optional :neighbor_info, :message, 11, "meshtastic.ModuleConfig.NeighborInfoConfig"
      optional :ambient_lighting, :message, 12, "meshtastic.ModuleConfig.AmbientLightingConfig"
      optional :detection_sensor, :message, 13, "meshtastic.ModuleConfig.DetectionSensorConfig"
      optional :paxcounter, :message, 14, "meshtastic.ModuleConfig.PaxcounterConfig"
      optional :version, :uint32, 8
    end
  end
end

module Meshtastic
  LocalConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.LocalConfig").msgclass
  LocalModuleConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.LocalModuleConfig").msgclass
end
