# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mqtt.proto

require 'google/protobuf'

require 'meshtastic/config_pb'
require 'meshtastic/mesh_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/mqtt.proto", :syntax => :proto3) do
    add_message "meshtastic.ServiceEnvelope" do
      optional :packet, :message, 1, "meshtastic.MeshPacket"
      optional :channel_id, :string, 2
      optional :gateway_id, :string, 3
    end
    add_message "meshtastic.MapReport" do
      optional :long_name, :string, 1
      optional :short_name, :string, 2
      optional :role, :enum, 3, "meshtastic.Config.DeviceConfig.Role"
      optional :hw_model, :enum, 4, "meshtastic.HardwareModel"
      optional :firmware_version, :string, 5
      optional :region, :enum, 6, "meshtastic.Config.LoRaConfig.RegionCode"
      optional :modem_preset, :enum, 7, "meshtastic.Config.LoRaConfig.ModemPreset"
      optional :has_default_channel, :bool, 8
      optional :latitude_i, :sfixed32, 9
      optional :longitude_i, :sfixed32, 10
      optional :altitude, :int32, 11
      optional :position_precision, :uint32, 12
      optional :num_online_local_nodes, :uint32, 13
    end
  end
end

module Meshtastic
  ServiceEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.ServiceEnvelope").msgclass
  MapReport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.MapReport").msgclass
end
