# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/remote_hardware.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/remote_hardware.proto", :syntax => :proto3) do
    add_message "meshtastic.HardwareMessage" do
      optional :type, :enum, 1, "meshtastic.HardwareMessage.Type"
      optional :gpio_mask, :uint64, 2
      optional :gpio_value, :uint64, 3
    end
    add_enum "meshtastic.HardwareMessage.Type" do
      value :UNSET, 0
      value :WRITE_GPIOS, 1
      value :WATCH_GPIOS, 2
      value :GPIOS_CHANGED, 3
      value :READ_GPIOS, 4
      value :READ_GPIOS_REPLY, 5
    end
  end
end

module Meshtastic
  HardwareMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.HardwareMessage").msgclass
  HardwareMessage::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.HardwareMessage.Type").enummodule
end
