# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/rtttl.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/rtttl.proto", :syntax => :proto3) do
    add_message "meshtastic.RTTTLConfig" do
      optional :ringtone, :string, 1
    end
  end
end

module Meshtastic
  RTTTLConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.RTTTLConfig").msgclass
end
