# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/storeforward.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/storeforward.proto", :syntax => :proto3) do
    add_message "meshtastic.StoreAndForward" do
      optional :rr, :enum, 1, "meshtastic.StoreAndForward.RequestResponse"
      oneof :variant do
        optional :stats, :message, 2, "meshtastic.StoreAndForward.Statistics"
        optional :history, :message, 3, "meshtastic.StoreAndForward.History"
        optional :heartbeat, :message, 4, "meshtastic.StoreAndForward.Heartbeat"
        optional :text, :bytes, 5
      end
    end
    add_message "meshtastic.StoreAndForward.Statistics" do
      optional :messages_total, :uint32, 1
      optional :messages_saved, :uint32, 2
      optional :messages_max, :uint32, 3
      optional :up_time, :uint32, 4
      optional :requests, :uint32, 5
      optional :requests_history, :uint32, 6
      optional :heartbeat, :bool, 7
      optional :return_max, :uint32, 8
      optional :return_window, :uint32, 9
    end
    add_message "meshtastic.StoreAndForward.History" do
      optional :history_messages, :uint32, 1
      optional :window, :uint32, 2
      optional :last_request, :uint32, 3
    end
    add_message "meshtastic.StoreAndForward.Heartbeat" do
      optional :period, :uint32, 1
      optional :secondary, :uint32, 2
    end
    add_enum "meshtastic.StoreAndForward.RequestResponse" do
      value :UNSET, 0
      value :ROUTER_ERROR, 1
      value :ROUTER_HEARTBEAT, 2
      value :ROUTER_PING, 3
      value :ROUTER_PONG, 4
      value :ROUTER_BUSY, 5
      value :ROUTER_HISTORY, 6
      value :ROUTER_STATS, 7
      value :ROUTER_TEXT_DIRECT, 8
      value :ROUTER_TEXT_BROADCAST, 9
      value :CLIENT_ERROR, 64
      value :CLIENT_HISTORY, 65
      value :CLIENT_STATS, 66
      value :CLIENT_PING, 67
      value :CLIENT_PONG, 68
      value :CLIENT_ABORT, 106
    end
  end
end

module Meshtastic
  StoreAndForward = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.StoreAndForward").msgclass
  StoreAndForward::Statistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.StoreAndForward.Statistics").msgclass
  StoreAndForward::History = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.StoreAndForward.History").msgclass
  StoreAndForward::Heartbeat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.StoreAndForward.Heartbeat").msgclass
  StoreAndForward::RequestResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.StoreAndForward.RequestResponse").enummodule
end
