# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/telemetry.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/telemetry.proto", :syntax => :proto3) do
    add_message "meshtastic.DeviceMetrics" do
      optional :battery_level, :uint32, 1
      optional :voltage, :float, 2
      optional :channel_utilization, :float, 3
      optional :air_util_tx, :float, 4
      optional :uptime_seconds, :uint32, 5
    end
    add_message "meshtastic.EnvironmentMetrics" do
      optional :temperature, :float, 1
      optional :relative_humidity, :float, 2
      optional :barometric_pressure, :float, 3
      optional :gas_resistance, :float, 4
      optional :voltage, :float, 5
      optional :current, :float, 6
      optional :iaq, :uint32, 7
      optional :distance, :float, 8
    end
    add_message "meshtastic.PowerMetrics" do
      optional :ch1_voltage, :float, 1
      optional :ch1_current, :float, 2
      optional :ch2_voltage, :float, 3
      optional :ch2_current, :float, 4
      optional :ch3_voltage, :float, 5
      optional :ch3_current, :float, 6
    end
    add_message "meshtastic.AirQualityMetrics" do
      optional :pm10_standard, :uint32, 1
      optional :pm25_standard, :uint32, 2
      optional :pm100_standard, :uint32, 3
      optional :pm10_environmental, :uint32, 4
      optional :pm25_environmental, :uint32, 5
      optional :pm100_environmental, :uint32, 6
      optional :particles_03um, :uint32, 7
      optional :particles_05um, :uint32, 8
      optional :particles_10um, :uint32, 9
      optional :particles_25um, :uint32, 10
      optional :particles_50um, :uint32, 11
      optional :particles_100um, :uint32, 12
    end
    add_message "meshtastic.Telemetry" do
      optional :time, :fixed32, 1
      oneof :variant do
        optional :device_metrics, :message, 2, "meshtastic.DeviceMetrics"
        optional :environment_metrics, :message, 3, "meshtastic.EnvironmentMetrics"
        optional :air_quality_metrics, :message, 4, "meshtastic.AirQualityMetrics"
        optional :power_metrics, :message, 5, "meshtastic.PowerMetrics"
      end
    end
    add_enum "meshtastic.TelemetrySensorType" do
      value :SENSOR_UNSET, 0
      value :BME280, 1
      value :BME680, 2
      value :MCP9808, 3
      value :INA260, 4
      value :INA219, 5
      value :BMP280, 6
      value :SHTC3, 7
      value :LPS22, 8
      value :QMC6310, 9
      value :QMI8658, 10
      value :QMC5883L, 11
      value :SHT31, 12
      value :PMSA003I, 13
      value :INA3221, 14
      value :BMP085, 15
      value :RCWL9620, 16
    end
  end
end

module Meshtastic
  DeviceMetrics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.DeviceMetrics").msgclass
  EnvironmentMetrics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.EnvironmentMetrics").msgclass
  PowerMetrics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.PowerMetrics").msgclass
  AirQualityMetrics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.AirQualityMetrics").msgclass
  Telemetry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.Telemetry").msgclass
  TelemetrySensorType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.TelemetrySensorType").enummodule
end
