# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/xmodem.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("meshtastic/xmodem.proto", :syntax => :proto3) do
    add_message "meshtastic.XModem" do
      optional :control, :enum, 1, "meshtastic.XModem.Control"
      optional :seq, :uint32, 2
      optional :crc16, :uint32, 3
      optional :buffer, :bytes, 4
    end
    add_enum "meshtastic.XModem.Control" do
      value :NUL, 0
      value :SOH, 1
      value :STX, 2
      value :EOT, 4
      value :ACK, 6
      value :NAK, 21
      value :CAN, 24
      value :CTRLZ, 26
    end
  end
end

module Meshtastic
  XModem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.XModem").msgclass
  XModem::Control = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("meshtastic.XModem.Control").enummodule
end
