# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nanopb.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("nanopb.proto", :syntax => :proto2) do
    add_message "NanoPBOptions" do
      optional :max_size, :int32, 1
      optional :max_length, :int32, 14
      optional :max_count, :int32, 2
      optional :int_size, :enum, 7, "IntSize", default: 0
      optional :type, :enum, 3, "FieldType", default: 0
      optional :long_names, :bool, 4, default: true
      optional :packed_struct, :bool, 5, default: false
      optional :packed_enum, :bool, 10, default: false
      optional :skip_message, :bool, 6, default: false
      optional :no_unions, :bool, 8, default: false
      optional :msgid, :uint32, 9
      optional :anonymous_oneof, :bool, 11, default: false
      optional :proto3, :bool, 12, default: false
      optional :proto3_singular_msgs, :bool, 21, default: false
      optional :enum_to_string, :bool, 13, default: false
      optional :fixed_length, :bool, 15, default: false
      optional :fixed_count, :bool, 16, default: false
      optional :submsg_callback, :bool, 22, default: false
      optional :mangle_names, :enum, 17, "TypenameMangling", default: 0
      optional :callback_datatype, :string, 18, default: "pb_callback_t"
      optional :callback_function, :string, 19, default: "pb_default_field_callback"
      optional :descriptorsize, :enum, 20, "DescriptorSize", default: 0
      optional :default_has, :bool, 23, default: false
      repeated :include, :string, 24
      repeated :exclude, :string, 26
      optional :package, :string, 25
      optional :type_override, :enum, 27, "google.protobuf.FieldDescriptorProto.Type"
      optional :sort_by_tag, :bool, 28, default: true
      optional :fallback_type, :enum, 29, "FieldType", default: 1
    end
    add_enum "FieldType" do
      value :FT_DEFAULT, 0
      value :FT_CALLBACK, 1
      value :FT_POINTER, 4
      value :FT_STATIC, 2
      value :FT_IGNORE, 3
      value :FT_INLINE, 5
    end
    add_enum "IntSize" do
      value :IS_DEFAULT, 0
      value :IS_8, 8
      value :IS_16, 16
      value :IS_32, 32
      value :IS_64, 64
    end
    add_enum "TypenameMangling" do
      value :M_NONE, 0
      value :M_STRIP_PACKAGE, 1
      value :M_FLATTEN, 2
      value :M_PACKAGE_INITIALS, 3
    end
    add_enum "DescriptorSize" do
      value :DS_AUTO, 0
      value :DS_1, 1
      value :DS_2, 2
      value :DS_4, 4
      value :DS_8, 8
    end
  end
end

NanoPBOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NanoPBOptions").msgclass
FieldType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FieldType").enummodule
IntSize = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IntSize").enummodule
TypenameMangling = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TypenameMangling").enummodule
DescriptorSize = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DescriptorSize").enummodule
